version: '2.1'

services:
  booking_module:
    image: booking_module
    environment:
      MYSQL_USER: root
      MYSQL_HOST: database
      MYSQL_DATABASE: bookings
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: YOUR_PASSWORD_HERE!
    depends_on:
      - 'database'
      - 'database_seed'
    build: .
    ports:
      - 3003:3003

  database_seed:
    image: db-seed
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: "YOUR_PASSWORD_HERE!"
    build: .
    depends_on:
      database:
        condition: service_healthy
    command: "node database/seed.js"
      
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=YOUR_PASSWORD_HERE!
      - MYSQL_DATABASE=bookings
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 3
    ports:
      - 33306:3306