version: 3
jobs:
  build:
    docker:
      - image: circleci/node:8.15
      - image: circleci/mysql:5.7
        environment: 
          MYSQL_DATABASE: 'bookings'
          MYSQL_RANDOM_ROOT_PASSWORD: yes
    
    working_directory: ~/repo

    steps:
      - checkout
      - run: "npm install"
      - run: "npm run build"
      - run: "npm run seed"
      - run: "npm run test"
